---
kind: pipeline
type: docker
name: container

platform:
  os: linux
  arch: amd64

steps:
  - name: security-build
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      dockerfile: Dockerfile
      output: type=oci,dest=oci/${DRONE_REPO_NAME},tar=false
      repo: owncloudops/${DRONE_REPO_NAME}

  - name: security-scan
    image: ghcr.io/aquasecurity/trivy
    commands:
      - trivy -v
      - trivy image --input oci/${DRONE_REPO_NAME}
    environment:
      TRIVY_EXIT_CODE: 1
      TRIVY_IGNORE_UNFIXED: True
      TRIVY_NO_PROGRESS: True
      TRIVY_SEVERITY: HIGH,CRITICAL
      TRIVY_TIMEOUT: 1m
      TRIVY_SKIP_FILES: /usr/local/bin/gomplate
      TRIVY_SKIP_DIRS: /var/www/onlyoffice/documentserver/dictionaries,/var/www/onlyoffice/documentserver/sdkjs-plugins
    depends_on:
      - security-build

  - name: changelog
    image: quay.io/thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}
      - cat CHANGELOG.md
    depends_on:
      - security-build

  - name: publish-dockerhub
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      dockerfile: Dockerfile
      auto_tag: True
      password:
        from_secret: docker_password
      repo: owncloudops/${DRONE_REPO_NAME}
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
    depends_on:
      - changelog

  - name: publish-quay
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      dockerfile: Dockerfile
      auto_tag: True
      password:
        from_secret: quay_password
      registry: quay.io
      repo: quay.io/owncloudops/${DRONE_REPO_NAME}
      username:
        from_secret: quay_username
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
    depends_on:
      - changelog

  - name: publish-registry
    image: docker.io/owncloudci/drone-docker-buildx:1
    settings:
      dockerfile: Dockerfile.ee
      auto_tag: True
      password:
        from_secret: registry_password
      registry: registry.owncloud.com
      repo: registry.owncloud.com/${DRONE_REPO_NAME}/${DRONE_REPO_NAME}-ee
      username:
        from_secret: registry_username
    environment:
      BUILDKIT_NO_CLIENT_TOKEN: true
    when:
      ref:
        - refs/heads/main
        - refs/tags/**
    depends_on:
      - security-build

  - name: release
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      note: CHANGELOG.md
      overwrite: true
      title: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/**
    depends_on:
      - publish-dockerhub
      - publish-quay
      - publish-registry

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    environment:
      DOCKER_PASS:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: owncloudops/${DRONE_REPO_NAME}
    when:
      status:
        - success

  - name: pushrm-quay
    image: docker.io/chko/docker-pushrm:1
    environment:
      APIKEY__QUAY_IO:
        from_secret: quay_token
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/owncloudops/${DRONE_REPO_NAME}
    when:
      status:
        - success

  - name: notify
    image: docker.io/plugins/slack
    settings:
      channel:
        from_secret: rocketchat_chat_channel
      webhook:
        from_secret: rocketchat_chat_webhook
    when:
      status:
        - failure

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - container
